### ISSUE TITLE
Fine Tuning Code

### ISSUE THREAD

**Issue by Shivansh-Srivastava-techolution** [CASIA-IVA-Lab/FastSAM#10]
Hey,
Huge thanks for such a great repo that you have made, just wanted to know if it can be fine tuned for specific purposes, it would be great if you could provide code to fine tune the model on COCO dataset.

**Comment by unriddler** [comment]
Looking forward to the training code.

**Comment by EveningLin** [comment]
@zxDeepDiver  Looking forward to the training code+1

**Comment by Xelawk** [comment]
Looking forward to the training code+2

**Comment by githublqs** [comment]
Looking forward to the training code+3

**Comment by Zr2223** [comment]
Looking forward to the training code+4

**Comment by beyoursel** [comment]
Looking forward to the training code+5

**Comment by mertikinci** [comment]
Looking forward to the training code+6

**Comment by songbingze** [comment]
Looking forward to the training code+7

**Comment by j0987834204** [comment]
Looking forward to the training code+8

**Comment by AAAAAAAyq** [comment]
Thanks very much for all of you for your attention! **Training and fine-tuning codes will be put together and released soon!**

> Hey, Huge thanks for such a great repo that you have made, just wanted to know if it can be fine tuned for specific purposes, it would be great if you could provide code to fine tune the model on COCO dataset.

**Comment by Sijie-L** [comment]
> Thanks very much for all of you for your attention! **Training and fine-tuning codes will be put together and released soon!**
> 
> > Hey, Huge thanks for such a great repo that you have made, just wanted to know if it can be fine tuned for specific purposes, it would be great if you could provide code to fine tune the model on COCO dataset.

Could you kindly provide an expected date when you guys will release it? It will be greatly appreciated!!

**Comment by AT38875** [comment]
Hi @an-yongqi  I have mailed regarding the finetuning code. Could you please check and revert bask?

**Comment by zxDeepDiver** [comment]
Training code released: https://github.com/CASIA-IVA-Lab/FastSAM/blob/main/sa_hub/TRAIN.md
