### ISSUE TITLE
The channel of saved image should be "bgr" format in cv2 function 

### ISSUE THREAD

**Issue by zhangningboo** [CASIA-IVA-Lab/FastSAM#101]
With the dog.jpg image to test, the saved image channel format is wrong:
![image](https://github.com/CASIA-IVA-Lab/FastSAM/assets/110680007/c9ec6059-796c-430f-8e4b-c0c872344648)

this is because when plotting the mask result, the image format was changed in `prompt.py:107:  image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)` and saved with cv2 function in `prompt.py: 216: cv2.imwrite(output_path, result)`.
Before `prompt.py: 216: cv2.imwrite(output_path, result)`, should change channel format from `rgb` to `bgr` when use cv2 function to save image: `result = result[:, :, ::-1]`
![image](https://github.com/CASIA-IVA-Lab/FastSAM/assets/110680007/139768b7-10f0-4e79-9713-3ac8df6d4548)

**Comment by zxDeepDiver** [comment]
Thanks a lots for your contribution.
