### ISSUE TITLE
Training Code

### ISSUE THREAD

**Issue by Dreamer-LRZ** [CASIA-IVA-Lab/FastSAM#124]
Looking forward to your training code.

**Comment by zxDeepDiver** [comment]
Hi, you can email xu.zhao@nlpr.ia.ac.cn to get the code.

**Comment by QzYER** [comment]
I also want you to open source training code

**Comment by aganagan** [comment]
Same upstairs

**Comment by dijiupianhai9** [comment]
> 嗨，您可以通过电子邮件 [xu.zhao@nlpr.ia.ac.cn](mailto:xu.zhao@nlpr.ia.ac.cn) 获取代码。

您好，我已经向您发送电子邮件了，望回复！

**Comment by QzYER** [comment]
think you&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CASIA-IVA-Lab/FastSAM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月15日(星期二) 中午1:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CASIA-IVA-Lab/FastSAM] Training Code (Issue #124)





  
嗨，您可以通过电子邮件 ***@***.*** 获取代码。
  
您好，我已经向您发送电子邮件了，望回复！

**Comment by dijiupianhai9** [comment]
> Hi, you can email [xu.zhao@nlpr.ia.ac.cn](mailto:xu.zhao@nlpr.ia.ac.cn) to get the code.

Hello, I have sent an email to you, hope to reply!

**Comment by Mxbonn** [comment]
+1 for open source training code.
