### ISSUE TITLE
Great work! would you like to add this to ultralytics models HUB?

### ISSUE THREAD

**Issue by AyushExel** [CASIA-IVA-Lab/FastSAM#13]
Hey guys,
great work on this. I'm one of the co-authors of Ultralytics YOLOv8 and was wondering if you'd like to add support for fast SAM to Ultralytics models HUB here -> https://docs.ultralytics.com/models/
I'd be happy to help. Thanks!

**Comment by berry-ding** [comment]
Thank you for your suggestion! We are delighted to add FastSAM to the Ultralytics models HUB for wider use. We will get to work on this as soon as possible.

**Comment by sunmouren** [comment]
Can't a 12GB GPU run?
![image](https://github.com/CASIA-IVA-Lab/FastSAM/assets/30149424/bfda8052-794d-44f4-b873-c428cf4c2970)
Inference has the following error:：
![image](https://github.com/CASIA-IVA-Lab/FastSAM/assets/30149424/c623ec03-04e2-4105-8f20-6b1ae55fccfc)
