### ISSUE TITLE
如何对FastSAM剪枝

### ISSUE THREAD

**Issue by arvin506** [CASIA-IVA-Lab/FastSAM#131]
请问如何对FastSAM-x.pt剪枝操作呢？我尝试了prune.global_unstructured ，结果失败了

**Comment by zxDeepDiver** [comment]
目前对于卷积神经网络的剪枝，一般以结构化剪枝更为实用，且一般都需要简直后训练微调。如果您有训练资源和数据，可以参考我们团队发布的剪枝工具包中对yolov5的剪枝教程，https://www.yuque.com/zhaoxu-scxqc/easy-pruner/ausdv8

**Comment by zxDeepDiver** [comment]
https://www.yuque.com/zhaoxu-scxqc/easy-pruner/bw0kuv

**Comment by zxDeepDiver** [comment]
https://www.yuque.com/zhaoxu-scxqc/easy-pruner/uk0z8d

**Comment by arvin506** [comment]
谢谢您的解答
