### ISSUE TITLE
Memory use kept adding

### ISSUE THREAD

**Issue by Rong-Tao** [CASIA-IVA-Lab/FastSAM#136]
I am connecting the inference code to a live camera and do everything segmentation online. I didn't check the memory use until my laptop froze and I have to force reboot.

I was using opencv to direct live frames into the inference API and it works fine with other APIs.

Here is the main loop, cap can be simply obtained by: `cap = cv2.VideoCapture(0)`

    def show_window(cap, model):
          cv2.namedWindow("window", 1)
          prev_time = 0
          while True:
              ret, BGR_frame = cap.read()
              if not ret:
                  print("Failed to grab frame")
                  break
  
              out = segment_everything(BGR_frame, model)
        
              # Calculate FPS
              cur_time = time.time()
              time_diff = cur_time - prev_time
              prev_time = cur_time
              
              if time_diff > 0:  # To avoid division by zero
                  fps = 1.0 / time_diff
              else:
                  fps = 0.0
              
              # Draw the FPS on the output frame
              cv2.putText(out, f'FPS: {fps:.2f}', (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2)
              
              cv2.imshow('Window (Press q to quit)', out)
              
              c = cv2.waitKey(1)
              if c & 0xFF == ord('q'):
                  break
        cv2.destroyAllWindows()
`

**Comment by BrunoGeorgevich** [comment]
Hello @Rong-Tao, the comment that I've made in #182 possibly will help you.

Let me know if it was helpful.

Best regards.

**Comment by Rong-Tao** [comment]
Thanks!
