### ISSUE TITLE
FastSAM batch inference?

### ISSUE THREAD

**Issue by Herick-Asmani** [CASIA-IVA-Lab/FastSAM#14]
Does FastSAM support batch inference on segment everything mode?

**Comment by AAAAAAAyq** [comment]
> Does FastSAM support batch inference on segment everything mode?

Yes, FastSAM supports batch inference. Unlike SAM, FastSAM's inference speed in Everything mode is not affected by point number, and it can directly segment the whole image by the anchor points. Moreover, FastSAM also supports batch segmentation for multiple images. We will release a demo of batch inference soon.

**Comment by daminnock** [comment]
Hi @an-yongqi .

Hi @an-yongqi, I have an additional question.

 Is FASTSAM able to segment batches of bounding boxes also?

In the original SAM model during inference if you indicate n bounding boxes for a single image, you will receive n masks.

**Comment by kevinchan04** [comment]
Hi, could you mind tell how to inference in batch? I put a torch tensor shape in BHWC in to the model but it will return the error message that "No object detected." and "list index out of range". Could you give any debug direction? Thank you!
