### ISSUE TITLE
License when using ultralytics underneath

### ISSUE THREAD

**Issue by trathpai** [CASIA-IVA-Lab/FastSAM#151]
Congratulations for good work.

I can see underneath code uses Ultralytics code which has AGPL-3.0 license. So how does repository turn out to be Apache-2.0 license?

Thanks

**Comment by glenn-jocher** [comment]
@trathpai yes this is a great point! I've submitted a PR to the authors to update the FastSAM license to AGPL-3.0 in https://github.com/CASIA-IVA-Lab/FastSAM/pull/184
