### ISSUE TITLE
Name of objects FastSAM

### ISSUE THREAD

**Issue by TiagoHiray** [CASIA-IVA-Lab/FastSAM#154]
Hey guys, is it possible to return the name of the objects detected same as YoloV8? If so, how?

**Comment by HtwoOtwo** [comment]
Hi, you can try:
```
# Run inference on an image
everything_results = model(source, device='cpu', retina_masks=True, imgsz=1024, conf=0.4, iou=0.9)
print(everything_results[0].names)
```
 to get the name of objects. But there is only one class:
`{0: 'object'}` 
Also you can use `everything_results[0].masks`  to get masks. 
Hope it will help you!

**Comment by TiagoHiray** [comment]
> Hi, you can try:
> 
> ```
> # Run inference on an image
> everything_results = model(source, device='cpu', retina_masks=True, imgsz=1024, conf=0.4, iou=0.9)
> print(everything_results[0].names)
> ```
> 
> to get the name of objects. But there is only one class: `{0: 'object'}` Also you can use `everything_results[0].masks` to get masks. Hope it will help you!

Thanks!
