### ISSUE TITLE
Supress print output

### ISSUE THREAD

**Issue by CheremyP** [CASIA-IVA-Lab/FastSAM#159]
Currently, when I run the following :

>       everything_results = self.model(IMAGE_PATH, device=self.DEVICE, retina_masks=True, imgsz=1024, conf=0.4, iou=0.9)
>       prompt_process = FastSAMPrompt(IMAGE_PATH, everything_results, device=self.DEVICE)
>       masks = prompt_process.point_prompt(points=input_point, pointlabel=[1])

It always prints the format below

- 0: 576x1024 21 objects, 91.3ms
- Speed: 12.0ms preprocess, 91.3ms inference, 15.3ms postprocess per image at shape (1, 3, 1024, 1024)

How do I turn off the print statements as I'm only interested in the masks?

**Comment by YamagamiH** [comment]
It looks like a YOLO specification. You can turn off the print by adding the following args.(verbose=False)
```
  everything_results = self.model(IMAGE_PATH, device=self.DEVICE, retina_masks=True, imgsz=1024, conf=0.4, iou=0.9, verbose=False)
  prompt_process = FastSAMPrompt(IMAGE_PATH, everything_results, device=self.DEVICE)
  masks = prompt_process.point_prompt(points=input_point, pointlabel=[1])
  ```
