### ISSUE TITLE
About the training resources and time

### ISSUE THREAD

**Issue by ywher** [CASIA-IVA-Lab/FastSAM#164]
Hi, nice work to follow.
I'd like to know what GPU resources are approximately required to train FastSAM from scratch to achieve the results mentioned in the paper. How many GPUs, how much VRAM, and roughly how long would the training take?
Looking for your reply, thanks!

**Comment by zxDeepDiver** [comment]
Hi, GPU memory 40+G, CPU memory: about 2T.

**Comment by JingLinWuu** [comment]
> Hi, GPU memory 40+G, CPU memory: about 2T.

Is it 2TB of memory or 2TB of storage space?

**Comment by Armadillooutfitter** [comment]
same
