### ISSUE TITLE
Problem with cuda (works perfectly on cpu)

### ISSUE THREAD

**Issue by vilemil** [CASIA-IVA-Lab/FastSAM#166]
Hello.

I tried to test the basic model with a few input image. When i run the code in Cpu everything okay.

`ann = prompt_process.everything_prompt()
`

ann type is Tensor, but when I try to run with device = cuda; or cuda:0, cuda:1... ann type is an empty list. 
torch.cuda.is_available() is True, so I have an available Gpu, and i downloaded the models from the official page. 

Do i miss something? 

//Windows11, Nvidia 3070ti, conda

Thanks.

**Comment by liujingangel** [comment]
I met the same problem when infering custom data. however it is successful with cuda: 0 when using default image from "images" folder .

**Comment by wangxinyu6666** [comment]
Have you solved the issue? I have the same problem as you. Also the image is small ( this project provides), it can work perfectly, but when the image is big (my image is 1800*4000), the ann of output is None.

**Comment by vilemil** [comment]
> Have you solved the issue? I have the same problem as you. Also the image is small ( this project provides), it can work perfectly, but when the image is big (my image is 1800*4000), the ann of output is None.

Yes. Torchvision reinstall solved the issue (for me).
