### ISSUE TITLE
Update License to AGPL-3.0 to Align with Ultraltyics YOLOv8

### ISSUE THREAD

**Issue by glenn-jocher** [CASIA-IVA-Lab/FastSAM#185]
@zxDeepDiver @berry-ding @YinglongDu @uahic and FastSAM team,

We've identified an important licensing discrepancy in the FastSAM repository in relation to its utilization of the YOLOv8 model. YOLOv8 is [AGPL-3.0 licensed](https://github.com/ultralytics/ultralytics/blob/main/LICENSE), and the current license of FastSAM does not mirror this. In order to comply with the licensing terms set by Ultralytics for YOLOv8, the FastSAM repository must be updated to reflect the AGPL-3.0 license.

This alignment is not only a legal obligation but also a commitment to uphold the standards of software integrity and responsible usage that Ultralytics embodies. The adaptation of the AGPL-3.0 license for FastSAM ensures all users and contributors remain in agreement with the terms under which YOLOv8 is distributed.

I've submitted PR https://github.com/CASIA-IVA-Lab/FastSAM/pull/184 for this license update to amend the FastSAM license. This will safeguard both Ultralytics’ and FastSAM’s users’ interests and ensure continued collaborative success.

Thank you for your immediate attention to this critical matter.

**Comment by zxDeepDiver** [comment]
Thanks a lot for your correcting.
