### ISSUE TITLE
FastSAM not making any detections on default images

### ISSUE THREAD

**Issue by DanielGinnArkeus** [CASIA-IVA-Lab/FastSAM#197]
I have not been able to get FastSAM to produce any output images, and have tracked it down to FastSAM making no detections. I have replicated this issue across two separate computers and on the Google Colab example.

**Comment by hudsonb22** [comment]
I also had this issue and your solution worked, changed the `fastsam/predict.py` file. Thanks!

**Comment by berry-ding** [comment]
hi, thank you for your interest. we have fixed this bug.
