### ISSUE TITLE
Suggestion - replace yolo8 with YoloNas for better performance

### ISSUE THREAD

**Issue by ofirkris** [CASIA-IVA-Lab/FastSAM#2]
Thanks for the great work!
Can you consider replacing yolo8 with YoloNas for better speed+performance?

![image](https://github.com/CASIA-IVA-Lab/FastSAM/assets/9070477/8da22fd4-4dc7-47c6-8059-8e08a285cb5a)

**Comment by zxDeepDiver** [comment]
Thank you for your good idea. We think it is a possible way to improve the performance.
