### ISSUE TITLE
Is Yolact anchor based or anchor free ?

### ISSUE THREAD

**Issue by surefyyq** [CASIA-IVA-Lab/FastSAM#25]
Thanks for the great engineering application research ！

I see the Yolo-seg series models completely borrow the idea of coefficientized masks from Yolact. 

In your paper 3.2 section saying about yolov8: _The updated Head module embraces a decoupled structure, separating classification and detection heads, and shifts from Anchor-Based to Anchor-Free._
And I'm wondering, does the threshold crop step in Yolact makes the yolo-seg architecture back to an Anchor-Based method?

**Comment by YinglongDu** [comment]
Thank you for your attention, yolov8 uses the method of anchor-free, which is mainly applied to detect branches, and there is no effect on segment branches, indeed Yolov8-seg uses anchor-free in the threshold crop step, I hope it can solve your doubts.:blush:

**Comment by AAAAAAAyq** [comment]
We would close this issue for now to keep the issue tracker organized. However, if the problem persists or if you have any further questions, please feel free to comment here or open a new issue. We value your input and are happy to assist further.

**Comment by Ragnar7982** [comment]
@Boatsure  Hello, did you figure it out yet? Here is command I ran: 
python eval.py --trained_model=weights/yolact_base_54_800000.pth --score_threshold=0.15 --top_k=15 --image=image/test2.jpg --mask_proto_debug --display_lincomb DISPLAY_LINCOMB
But it said:
eval.py: error: argument --display_lincomb: Boolean value expected.
If I run python eval.py --trained_model=weights/yolact_base_54_800000.pth --score_threshold=0.15 --top_k=15 --image=image/test2.jpg --mask_proto_debug
It will only show result image(not the paper fig.5)
