### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by unriddler** [CASIA-IVA-Lab/FastSAM#26]
Hi author,
Will you release the code so we can have a try?

**Comment by zxDeepDiver** [comment]
The code is currently being organized to optimize its utility for downstream task fine-tuning scenarios. If you wish to promptly obtain the code for training or fine-tuning purposes, kindly reach out to us via email and specify your intended use case. We welcome your usage across various scenarios. For emailing, we recommend contacting us at xu.zhao@nlpr.ia.ac.cn.
