### ISSUE TITLE
can you provide a model download link of baidu cloud？

### ISSUE THREAD

**Issue by perfyperfect** [CASIA-IVA-Lab/FastSAM#28]
can you provide a model download link of baidu cloud？

**Comment by berry-ding** [comment]
Thank you for your interest in our work.
BaiduNetdisk 
url: https://pan.baidu.com/s/18KzBmOTENjByoWWR17zdiQ?pwd=0000 
passwd: 0000

**Comment by AAAAAAAyq** [comment]
> can you provide a model download link of baidu cloud？

I have updated the README.md to add a baidu cloud link in [model checkpoints](https://github.com/CASIA-IVA-Lab/FastSAM#model-checkpoints)
