### ISSUE TITLE
tensorrt inference?

### ISSUE THREAD

**Issue by machine52vision** [CASIA-IVA-Lab/FastSAM#29]

**Comment by ChuRuaNh0** [comment]
I converted pt to onnx, and to trt. But outputs infer are 2 tensors have shape (1,32,160,160) , (1,32,8400). I couldn't post process to get mask. Please help me.

**Comment by ChuRuaNh0** [comment]
I handled it. You can reference at link: [GitHub] (https://github.com/ChuRuaNh0/FastSam_Awsome_TensorRT). If it helpful with you, give me a star, thanks.

**Comment by thanhson28** [comment]
@ChuRuaNh0 thank you, you saved ton of time

**Comment by yuanjiechen** [comment]
@ChuRuaNh0 thank you!
For better performance, add an "INMSLayer" at the end of network is a better choice!

**Comment by AAAAAAAyq** [comment]
> I handled it. You can reference at link: [GitHub] (https://github.com/ChuRuaNh0/FastSam_Awsome_TensorRT). If it helpful with you, give me a star, thanks.

Thanks for your contribution! We will add [FastSAM_Awesome_TensorRT](https://github.com/ChuRuaNh0/FastSam_Awsome_TensorRT) link to [README.md](https://github.com/CASIA-IVA-Lab/FastSAM/blob/main/README.md), so that more people can benefit from your contribution.

**Comment by ChuRuaNh0** [comment]
@AAAAAAAyq I'm appreciate. It's great to hear that.

**Comment by FT115** [comment]
> I handled it. You can reference at link: [GitHub] (https://github.com/ChuRuaNh0/FastSam_Awsome_TensorRT). If it helpful with you, give me a star, thanks.

Great Work! I want to know the inference speed and your device  when you use the ONNX or TRT. Looking forward to your reply
