### ISSUE TITLE
how finetune fastsam on my datasets?

### ISSUE THREAD

**Issue by machine52vision** [CASIA-IVA-Lab/FastSAM#30]

**Comment by AAAAAAAyq** [comment]
@machine52vision Please wait for a moment. **Fine-tuning code will be released soon!**

**Comment by zxDeepDiver** [comment]
The code is currently being organized to optimize its utility for downstream task fine-tuning scenarios. If you wish to promptly obtain the code for training or fine-tuning purposes, kindly reach out to us via email and specify your intended use case. We welcome your usage across various scenarios. For emailing, we recommend contacting us at xu.zhao@nlpr.ia.ac.cn.

**Comment by piyushw0203** [comment]
any updates?
