### ISSUE TITLE
the model outputs only masks, no labels?

### ISSUE THREAD

**Issue by kobic8** [CASIA-IVA-Lab/FastSAM#33]
Are you also planning combining this model to Grounding-DINO by IDEA?

**Comment by AAAAAAAyq** [comment]
> Are you also planning combining this model to Grounding-DINO by IDEA?

Yes, the current FastSAM only has masks, not labels, which is the direction of our future research. 

Currently FastSAM has been combined with Grounding-DINO. Thanks a lot to [Grounding-SAM](https://github.com/IDEA-Research/Grounded-Segment-Anything) for Combining Grounding-DINO with FastSAM in [Grounded-FastSAM](https://github.com/IDEA-Research/Grounded-Segment-Anything/tree/main/ FastSAM) 🌹.
