### ISSUE TITLE
cog是啥库?

### ISSUE THREAD

**Issue by orderer0001** [CASIA-IVA-Lab/FastSAM#34]
向作者致敬，predict文件中import cog，这个cog是什么？也是pip安装的嘛

**Comment by AAAAAAAyq** [comment]
> 向作者致敬，predict文件中import cog，这个cog是什么？也是pip安装的嘛

感谢支持，predict.py 和 cog.yaml 是由 [Chenxi](https://chenxwh.github.io/) 提供的关于 Replicate demo 的文件，具体使用可见 [Cog](https://github.com/replicate/cog)。如果你只是想在本地运行FastSAM代码，无需安装cog库。

Thanks for the support, predict.py and cog.yaml are files provided by [Chenxi](https://chenxwh.github.io/) about Replicate demo, see [Cog](https://github.com/replicate/cog) for specific use. If you just want to run FastSAM code locally, there is no need to install the cog library.
