### ISSUE TITLE
Interface compatibility

### ISSUE THREAD

**Issue by da-wad** [CASIA-IVA-Lab/FastSAM#4]
Nice work!

I'd like to suggest that you create a compatible interface to SAM itself, i.e. a drop-in replacement to `SamAutomaticMaskGenerator` which would make it easier for people to start using this.

**Comment by AAAAAAAyq** [comment]
> Nice work!
> 
> I'd like to suggest that you create a compatible interface to SAM itself, i.e. a drop-in replacement to `SamAutomaticMaskGenerator` which would make it easier for people to start using this.

Thanks for your suggestion. We will package it as a SAM-like encoder and decoder in the near future to make it easier for people to start subsequent development.
