### ISSUE TITLE
Multiple objects text prompt 

### ISSUE THREAD

**Issue by pepijnob** [CASIA-IVA-Lab/FastSAM#40]
Is it possible with the text prompt that it detects multiple objects ? (e.g., "people" will find all people in the image)

**Comment by rentainhe** [comment]
You can try to use Grounding-DINO to generate box prompt for this situation, we have already implemented this in [Grounded-Segment-Anything](https://github.com/IDEA-Research/Grounded-Segment-Anything/tree/main/FastSAM) @pepijnob

**Comment by AAAAAAAyq** [comment]
> You can try to use Grounding-DINO to generate box prompt for this situation, we have already implemented this in [Grounded-Segment-Anything](https://github.com/IDEA-Research/Grounded-Segment-Anything/tree/main/FastSAM) @pepijnob

@rentainhe Thanks again for helping us to combine Grounding-DINO with FastSAM in [Grounded-FastSAM](https://github.com/IDEA-Research/Grounded-Segment-Anything/tree/main/FastSAM). It is a nice work.

**Comment by rentainhe** [comment]
> > You can try to use Grounding-DINO to generate box prompt for this situation, we have already implemented this in [Grounded-Segment-Anything](https://github.com/IDEA-Research/Grounded-Segment-Anything/tree/main/FastSAM) @pepijnob
> 
> @rentainhe Thanks again for helping us to combine Grounding-DINO with FastSAM in [Grounded-FastSAM](https://github.com/IDEA-Research/Grounded-Segment-Anything/tree/main/FastSAM). It is a nice work.

You're welcome! FastSAM is a great job! We will combine it with RAM too to improve the speed of the auto labelling process!

**Comment by AAAAAAAyq** [comment]
Hi @pepijnob,

I would like to close this issue for now to keep the issue tracker organized. However, if the problem persists or if you have any further questions, please feel free to comment here or open a new issue. We value your input and are happy to assist further. 

Thank you for your understanding!

Best Regards,
Yongqi An
