### ISSUE TITLE
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/usr/local/lib/python3.8/site-packages/cv2/qt/plugins" even though it was found

### ISSUE THREAD

**Issue by GELIELEO** [CASIA-IVA-Lab/FastSAM#42]

**Comment by Abhishek-Quidich** [comment]
For Ubuntu: following command will install some packages to solve this isse.
sudo apt-get install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev


Option 2(works for any OS) :  install opencv-python-headless. using pip, pip install opencv-python-headless

**Comment by AAAAAAAyq** [comment]
Hi @GELIELEO,

I noticed that the issue you reported seems to be resolved based on Abhishek-Quidich's last response, and there hasn't been any follow-up from your end. 

I would like to close this issue for now to keep the issue tracker organized. However, if the problem persists or if you have any further questions, please feel free to comment here or open a new issue. We value your input and are happy to assist further. 

Thank you for your understanding!

Best Regards,
Yongqi An
