### ISSUE TITLE
CoreML export with variable Input Size

### ISSUE THREAD

**Issue by okdha1234** [CASIA-IVA-Lab/FastSAM#56]
Hi, 
Can someone help in understanding how to give variable input image sizes to FastSAM model exported in onnx format, currently it takes only (1024,1024) size image which is leading to mismatch in desired outcome

**Comment by AAAAAAAyq** [comment]
Hi, @okdha1234 

#46 discusses the same issue and gives reference code that will hopefully solve your problem.
