### ISSUE TITLE
Is only one box_prompt used in FastSAM?

### ISSUE THREAD

**Issue by j0987834204** [CASIA-IVA-Lab/FastSAM#58]
Hi, thank you very much for your research. 
Does box_prompt currently support only one box?

**Comment by berry-ding** [comment]
Hi @j0987834204, thank you for your interest in our work. We've just updated the bbox prompt code and added support for multi bbox prompting. You can refer to the relevant code for utilizing multi bbox prompting.

https://github.com/CASIA-IVA-Lab/FastSAM/blob/c7018b049ba5cf5709277dca9f6154968b16677c/segpredict.py#L26C1-L30C87
