### ISSUE TITLE
TypeError: torch._VariableFunctionsClass.meshgrid() got multiple values for keyword argument 'indexing'

### ISSUE THREAD

**Issue by dumppool** [CASIA-IVA-Lab/FastSAM#59]
Run the example script.   
python Inference.py --model_path  FastSAM-x.pt  --img_path  .\examples\dogs.jpg

File "d:\ProgramData\Anaconda3\envs\fastsam\lib\site-packages\torch\functional.py", line 504, in _meshgrid
    return _VF.meshgrid(tensors, **kwargs, indexing ='ij')  # type: ignore[attr-defined]
TypeError: torch._VariableFunctionsClass.meshgrid() got multiple values for keyword argument 'indexing'
Any one know how to solve it?

**Comment by berry-ding** [comment]
Hi @dumppool , this seems like an error from PyTorch. May I ask what your PyTorch version is? Could you provide the code or commands that you executed for our reference?

**Comment by AAAAAAAyq** [comment]
We would close this issue for now to keep the issue tracker organized. However, if the problem persists or if you have any further questions, please feel free to comment here or open a new issue. We value your input and are happy to assist further.
