### ISSUE TITLE
about the train code

### ISSUE THREAD

**Issue by yo-WASSUP** [CASIA-IVA-Lab/FastSAM#60]
Thanks for your work, does the training code mean that I can use my labeled segmented data containing one class to train a model that segments only that one class?

感谢您的工作，请问训练代码是指可以使用我包含一个类的已标注分割数据训练一个只分割这一个类的模型吗？

**Comment by zxDeepDiver** [comment]
Yes. 
是的

**Comment by Sijie-L** [comment]
So why in the code it says the training is not supported?

    def train(self, **kwargs):
        """Function trains models but raises an error as FastSAM models do not support training."""
        raise NotImplementedError("FastSAM models don't support training")

**Comment by zxDeepDiver** [comment]
> So why in the code it says the training is not supported?
> 
> ```
> def train(self, **kwargs):
>     """Function trains models but raises an error as FastSAM models do not support training."""
>     raise NotImplementedError("FastSAM models don't support training")
> ```

This version of codes does not support training. We are working to release the training codes recently.

**Comment by Rwik2000** [comment]
When can we expect the training code?

**Comment by zxDeepDiver** [comment]
> When can we expect the training code?

 If you wish to promptly obtain the code for training or fine-tuning purposes, kindly reach out to us via email and specify your intended use case. We welcome your usage across various scenarios. For emailing, we recommend contacting us at xu.zhao@nlpr.ia.ac.cn.
