### ISSUE TITLE
Can I use my own YOLOv8 model weights with FastSAM ? 

### ISSUE THREAD

**Issue by mertikinci** [CASIA-IVA-Lab/FastSAM#63]
I have tried to use a trained YOLOv8 models weights with FastSAM but it is raising an error about mismatching. I know you guys working on a fine-tune/train code right now but I was just curious about whether replacing the weights possible or not ? 

Thanks for a great work!

**Comment by zxDeepDiver** [comment]
Maybe the class number is not consistent?

**Comment by mertikinci** [comment]
my models class number is 4, do I have to make any more adjustments about it ? or do I need to train a model that has a fixed class number ?

**Comment by zxDeepDiver** [comment]
Generall, it is not suggested to use the model trained for other tasks in this code. Could you directly use you yolov8 codes in your project?

**Comment by mertikinci** [comment]
thanks for advice

**Comment by zxDeepDiver** [comment]
Hello. We will close this issue first. Feel free to reopen it if you have any questions.
