### ISSUE TITLE
Minor error

### ISSUE THREAD

**Issue by shersoni610** [CASIA-IVA-Lab/FastSAM#64]
Hello,

I am running the cat example given in the image folder. On MAC-M1, I get the following error:

 img_array = np.frombuffer(buf, dtype=np.uint8).reshape(rows, cols, 3)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: cannot reshape array of size 24883200 into shape (1920,1080,3)

can someone help?

**Comment by zxDeepDiver** [comment]
It seems you input a png file and it has the alpha channel.

**Comment by csv610** [comment]
I used the example in the folder. What should I do?

**Comment by zxDeepDiver** [comment]
> I used the example in the folder. What should I do?

Can you remove the alpha channel of your image? Only the rgb 3-channel is needed.

**Comment by shersoni610** [comment]
It is jpg file in the image folder.

**Comment by zxDeepDiver** [comment]
> It is jpg file in the image folder.

your image byte length is 1920*1080*4, I suggest you check the imread settings.

**Comment by berry-ding** [comment]
Hi @shersoni610, under MacOS-M1, Matplotlib has different default values. Please confirm that the following line of code can be executed. 
https://github.com/CASIA-IVA-Lab/FastSAM/blob/02d038259e997b6a92e9a8e8a2664979feafdacb/fastsam/prompt.py#L110C1-L111C40

**Comment by zxDeepDiver** [comment]
We will close this issue first. Feel free to reopen it if you have any questions.

**Comment by csv610** [comment]
Hello
I had to comment out two lines of  imwrite and the line above it to make the code work.



Sent from Yahoo Mail for iPhone


On Saturday, July 1, 2023, 1:20 AM, Wenchao Ding ***@***.***> wrote:




Hi @shersoni610, under MacOS-M1, Matplotlib has different default values. Please confirm that the following line of code can be executed.
https://github.com/CASIA-IVA-Lab/FastSAM/blob/02d038259e997b6a92e9a8e8a2664979feafdacb/fastsam/prompt.py#L110C1-L111C40
