### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'weights\\FastSAM.pt'

### ISSUE THREAD

**Issue by Gyearn** [CASIA-IVA-Lab/FastSAM#66]
I need help.I don't know why.
![bd2034906dba384369468fc8ce1d64c](https://github.com/CASIA-IVA-Lab/FastSAM/assets/138141565/fbef13ac-2c85-4fcd-ab35-0c98dc1eb339)

**Comment by zxDeepDiver** [comment]
Hi, please verify the existence of the file `FastSAM.pth` at the specified path.

**Comment by Gyearn** [comment]
感谢您的回信


不是权重文件的问题，当我修改fastsam/__init__.py 如下：

现在问题变为&nbsp;

我认为不是权重文件的问题，应该是路径的问题，但我找不到正确答案，




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CASIA-IVA-Lab/FastSAM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月2日(星期天) 下午4:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CASIA-IVA-Lab/FastSAM] FileNotFoundError: [Errno 2] No such file or directory: 'weights\\FastSAM.pt' (Issue #66)





 
Closed #66 as completed.

**Comment by Gyearn** [comment]
I can‘t find the fire FastSAM.pth，so What can I do？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CASIA-IVA-Lab/FastSAM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月2日(星期天) 下午4:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CASIA-IVA-Lab/FastSAM] FileNotFoundError: [Errno 2] No such file or directory: 'weights\\FastSAM.pt' (Issue #66)





 
Hi, please verify the existence of the file FastSAM.pth at the specified path.

**Comment by zxDeepDiver** [comment]
https://github.com/CASIA-IVA-Lab/FastSAM#model-checkpoints

**Comment by zxDeepDiver** [comment]
> I can‘t find the fire FastSAM.pth，so What can I do？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "CASIA-IVA-Lab/FastSAM" ***@***.***&gt;; 发送时间:&nbsp;2023年7月2日(星期天) 下午4:47 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [CASIA-IVA-Lab/FastSAM] FileNotFoundError: [Errno 2] No such file or directory: 'weights\\FastSAM.pt' (Issue #66) Hi, please verify the existence of the file FastSAM.pth at the specified path. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Have you downloaded the pth file?

**Comment by Gyearn** [comment]
Yes,I have downloaded ZIP




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CASIA-IVA-Lab/FastSAM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月2日(星期天) 下午5:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CASIA-IVA-Lab/FastSAM] FileNotFoundError: [Errno 2] No such file or directory: 'weights\\FastSAM.pt' (Issue #66)





  
I can‘t find the fire FastSAM.pth，so What can I do？
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "CASIA-IVA-Lab/FastSAM" @.&gt;; 发送时间:&nbsp;2023年7月2日(星期天) 下午4:47 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [CASIA-IVA-Lab/FastSAM] FileNotFoundError: [Errno 2] No such file or directory: 'weights\FastSAM.pt' (Issue #66) Hi, please verify the existence of the file FastSAM.pth at the specified path. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
Have you downloaded the pth file?

**Comment by Gyearn** [comment]
Failed download






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CASIA-IVA-Lab/FastSAM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月2日(星期天) 下午5:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CASIA-IVA-Lab/FastSAM] FileNotFoundError: [Errno 2] No such file or directory: 'weights\\FastSAM.pt' (Issue #66)





 
https://github.com/CASIA-IVA-Lab/FastSAM#model-checkpoints

**Comment by Gyearn** [comment]
I need you help me .This problem has been bothering me for two days, and I don't have the ability to solve it.
&nbsp;Thank&nbsp; you!






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月2日(星期天) 下午5:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CASIA-IVA-Lab/FastSAM] FileNotFoundError: [Errno 2] No such file or directory: &#39;weights\\FastSAM.pt&#39; (Issue #66)





 
https://github.com/CASIA-IVA-Lab/FastSAM#model-checkpoints

**Comment by Gyearn** [comment]
Can you send me FastSAM.pt directly?
Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CASIA-IVA-Lab/FastSAM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月2日(星期天) 晚上7:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CASIA-IVA-Lab/FastSAM] FileNotFoundError: [Errno 2] No such file or directory: 'weights\\FastSAM.pt' (Issue #66)





 
Reopened #66.

**Comment by NTUZZH** [comment]
You need download the Model Checkpoints and place it in the /weight, such as this /wight/ FastSAM-h

**Comment by Gyearn** [comment]
可以运行了
谢谢



---Original---
From: ***@***.***&gt;
Date: Sun, Jul 2, 2023 23:27 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [CASIA-IVA-Lab/FastSAM] FileNotFoundError: [Errno 2] No such fileor directory: 'weights\\FastSAM.pt' (Issue #66)




 
You need download the Model Checkpoints and place it in the /weight, such as this /wight/ FastSAM-h
