### ISSUE TITLE
Read multiple images at once

### ISSUE THREAD

**Issue by nomoneyExpection** [CASIA-IVA-Lab/FastSAM#68]
Can I read all the pictures in the folder at one time and use only one text prompt? I tried to do this, but an opencv error occurred. Is there a mistake in my operation or other reasons, because this operation is more realistic significance

**Comment by YinglongDu** [comment]
Thank you for your suggestion, currently, FastSAM does not support using one text prompt for multiple images, we will improve this feature later.:blush:
