### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by ajertec** [CASIA-IVA-Lab/FastSAM#69]
Thanks for you interesting work.

I have license question: How can FastSAM model be released under Apache license when the SA-1B training dataset is licensed under research only license + ultralytics yolo codebase under AGPL?

**Comment by zxDeepDiver** [comment]
We would like close this issue to keep the issue organized. Feel free to comment here or open a new issue or directly contact us by email. We value all of your suggestions.

**Comment by amitkumar-81** [comment]
FastSAM model can't be released under Apache license as underlying YOLOv8 is AGPL. This is misleading
