### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by dimsumham** [CASIA-IVA-Lab/FastSAM#7]
I'm getting this error when I'm trying to run pip. 

Installing collected packages: seaborn, ultralytics
ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'C:\\Python311\\Scripts\\ultralytics.exe' -> 'C:\\Python311\\Scripts\\ultralytics.exe.deleteme'

**Comment by zxDeepDiver** [comment]
Thank you for you intest on our work. We mainly deploy the codes in Linux. For Windows, you may search the [issues](https://github.com/ultralytics/ultralytics/issues?q=is%3Aissue+is%3Aopen+windows) of ultralytics for the answer.
