### ISSUE TITLE
Person Mask

### ISSUE THREAD

**Issue by Mahsa33** [CASIA-IVA-Lab/FastSAM#70]
Thanks for your great work.
How can I get only person(human) mask from an image?

**Comment by AAAAAAAyq** [comment]
Hey @Mahsa33,

If you want a specific person, you can use a more detailed description, such as "person with blue shirt". Or if you want all people in the image, you can try to use Grounding-DINO to generate box prompt for this situation, we have already implemented this in [Grounded-Segment-Anything](https://github.com/IDEA-Research/Grounded-Segment-Anything/tree/main/FastSAM) provided by Grounding-DINO.
