### ISSUE TITLE
I can't run the code!

### ISSUE THREAD

**Issue by yuhua666** [CASIA-IVA-Lab/FastSAM#77]
File "/root/FastSAM/fastsam/utils.py", line 17, in adjust_bboxes_to_image_border
    boxes[:, 0] = torch.where(boxes[:, 0] < threshold, 0, boxes[:, 0])  # x1
RuntimeError: expected scalar type long int but found float

**Comment by AAAAAAAyq** [comment]
You can watch this issue (#57). It can solve your problem.
