### ISSUE TITLE
detail command

### ISSUE THREAD

**Issue by mk622** [CASIA-IVA-Lab/FastSAM#79]
Original SAM model could command detail mask_generator as below,  
  mask_generator = SamAutomaticMaskGenerator(model=sam, points_per_side=48, pred_iou_thresh=0.43,
                                               stability_score_thresh=0.92, crop_n_layers=1,
                                               crop_n_points_downscale_factor=2, min_mask_region_area=1)

FastSAM also have function like this?

**Comment by YinglongDu** [comment]
Thanks for your attention. Yes, FastSAM has a similar function to SamAutomaticMaskGenerator.
```Python
    model = FastSAM("FastSAM model path")
    everything_results = model(
        img_path="image.jpg",
        device=args.device,
        retina_masks=args.retina,
        imgsz=1024,
        conf=0.25,
        iou=0.7    
        )
```
You can change the iou, conf hyperparameters to suit your needs.:blush:

**Comment by kingljl** [comment]
> Thanks for your attention. Yes, FastSAM has a similar function to SamAutomaticMaskGenerator.
> 
> ```python
>     model = FastSAM("FastSAM model path")
>     everything_results = model(
>         img_path="image.jpg",
>         device=args.device,
>         retina_masks=args.retina,
>         imgsz=1024,
>         conf=0.25,
>         iou=0.7    
>         )
> ```
> 
> You can change the iou, conf hyperparameters to suit your needs.:blush:

How can the mask of this function be broken down into multiple images when all the masks are placed in one image
