### ISSUE TITLE
Output Image - Colab

### ISSUE THREAD

**Issue by NigelHiggs30** [CASIA-IVA-Lab/FastSAM#8]
Why does the example script used in the Colab notebook save the final image in a downsized version? When I use my own custom photo, the resulting image dimensions are considerably smaller.

**Comment by AAAAAAAyq** [comment]
> Why does the example script used in the Colab notebook save the final image in a downsized version? When I use my own custom photo, the resulting image dimensions are considerably smaller.

Thank you for your feedback. We have updated the code for saving images and this issue has now been resolved. #https://github.com/CASIA-IVA-Lab/FastSAM/commit/3aa48c7250f8387e912e92f4e35b25c2dd8f8edb
