### ISSUE TITLE
the code  for  test Object proposal generation task ?

### ISSUE THREAD

**Issue by Anymake** [CASIA-IVA-Lab/FastSAM#83]
Can you  support the inference and evaluation AR@100 code  for  test Object proposal generation task ?

**Comment by zxDeepDiver** [comment]
Hello, you can email @berry-ding to get the codes.

**Comment by woshitiancai321** [comment]
> Can you support the inference and evaluation AR@100 code for test Object proposal generation task ?

Hello, have you received the evaluation code? Can you share it, please? Thank you.

**Comment by woshitiancai321** [comment]
> Can you support the inference and evaluation AR@100 code for test Object proposal generation task ?

please please please,please~~~
