### ISSUE TITLE
How to get the rect points of the bounding box of the mask?

### ISSUE THREAD

**Issue by Atomadeus** [CASIA-IVA-Lab/FastSAM#89]
我该如何获取通过point prompt得到的掩膜(mask)的边界框(bounding box)点坐标(rect points)？

How can I obtain the rect points of the bounding box of the mask obtained through point prompt?

**Comment by Atomadeus** [comment]
是这样的，我想做一个半自动标注工具，为我的YOLO模型提供数据，我希望实现的效果是点击图片上面的对象通过FastSAM进行分割然后得到边界框信息，这会比手动拉框要轻松很多，但是我现在无法直接得到mask的bounding box信息。

So, I want to create a semi-automatic annotation tool to provide data for my YOLO model. The desired outcome is to click on objects in the image, use FastSAM for segmentation, and obtain the bounding box information. This would be much easier than manually drawing boxes. However, I am currently unable to directly obtain the bounding box information for the mask.

**Comment by YinglongDu** [comment]
未来我们将丰富FastSAM输出MASK的结果，包括每一个Mask的边界框信息、置信度得分等等，敬请期待。
In the future, we will enrich the results of FastSAM output MASK, including the bounding box information, confidence score, etc. for each Mask, so stay tuned.😊

**Comment by Atomadeus** [comment]
非常感谢你能够及时回复

Thanks for your prompt reply.

**Comment by tsw123678** [comment]
> 是这样的，我提出一个半自动标注工具，为我的YOLO模型提供数据，我希望实现的效果是点击图片上面的对象通过FastSAM进行分割然后得到边界框信息，这会比手动拉框轻松很多，但是我现在无法直接获得掩码的边界框信息。
> 
> 所以，我想创建一个半自动注释工具来为我的 YOLO 模型提供数据。期望的结果是点击图像中的对象，使用FastSAM进行分割，并获取边界框信息。这比手动绘制方框要容易得多。但是，我目前无法直接获取蒙版的边界框信息。

Can you share this project? I am currently working on a reconstruction image related project, and your tool may help me. I will not use it for commercial purposes. If possible, thank you for sharing
