### ISSUE TITLE
FigureCanvasTkAgg 

### ISSUE THREAD

**Issue by enginksz** [CASIA-IVA-Lab/FastSAM#9]
Hello,

python Inference.py --model_path FastSAM-x.pt --img_path images/dogs.jpg

I got the following error when I ran it.

AttributeError: 'FigureCanvasTkAgg' object has no attribute 'renderer'

If anyone encounters this problem, they can add the following line to tools.py (line 171).

> buf = fig.canvas.draw()
buf = fig.canvas.tostring_rgb()

**Comment by AAAAAAAyq** [comment]
> buf = fig.canvas.draw()

Thanks for your contribution. We have [updated the code](https://github.com/CASIA-IVA-Lab/FastSAM/commit/e6d42e5176ff576082b55c721bec8843f7db7ad7) to avoid "AttributeError: 'FigureCanvasTkAgg' object has no attribute 'renderer'".
