### ISSUE TITLE
How to inference with c++ code?

### ISSUE THREAD

**Issue by happybear1015** [CASIA-IVA-Lab/FastSAM#90]

**Comment by bnascimento** [comment]
also interested

**Comment by Muneeb-Ahmed-Khan** [comment]
Interested.

**Comment by githublqs** [comment]
https://github.com/CASIA-IVA-Lab/FastSAM/issues/86#issuecomment-1626390622

**Comment by zxDeepDiver** [comment]
Since FastSAM is based on YOLOv8x-seg. FastSAM inference with c++ code is similar to the  inference of YOLOv8x-seg model, with little code implementation for the second stage.

**Comment by zxDeepDiver** [comment]
> [#86 (comment)](https://github.com/CASIA-IVA-Lab/FastSAM/issues/86#issuecomment-1626390622)

Hi, thanks for you comment. Is #86  implemented by C++?

**Comment by githublqs** [comment]
@zxDeepDiver yes，I use onnxruntime  c++ api  and opencv for inference

**Comment by zxDeepDiver** [comment]
> @zxDeepDiver yes，I use onnxruntime c++ api and opencv for inference

Great, maybe your experiences can help them.
