### ISSUE TITLE
YOLOV8 not accepting FastSAM-x.pt checkpoint

### ISSUE THREAD

**Issue by qevr** [CASIA-IVA-Lab/FastSAM#91]
Hi,

I wanted to load FastSAM-x.pt checkpoint on yolo model and fine tune from here on a dataset but YOLOV8 is not accepting FastSAM checkpoint. Does anyone know how can this checkpoint be loaded in YOLO for fine tuning ?

**Comment by zxDeepDiver** [comment]
You should choose yolov8x-seg model.

**Comment by qevr** [comment]
But then, I don't have that much data to train it , if I want to fine tune output from FastSAM on a very small set.

**Comment by zxDeepDiver** [comment]
Finetuing strategies are still being studied. Maybe the finetuning methods of many SAM related works can help you.

**Comment by qevr** [comment]
@zxDeepDiver Can you explain when fastsam is trained on a yolov8-seg.yaml checkpoint, why is it not accepting FastSAM-x.pt as checkpoint. Is some more architecture modification has been introduced other then of yolo for training ?
