### ISSUE TITLE
[Documentation Request] New download endpoint for FastSAM weights

### ISSUE THREAD

**Issue by capjamesg** [CASIA-IVA-Lab/FastSAM#92]
I am working on integrating FastSAM in a project on which I am working. Are you planning to distribute weights via HuggingFace or a direct download link? I would like to set up a build process that automatically downloads the weights on application setup and I'm not sure if that is possible with the Google Drive URLs available.

**Comment by berry-ding** [comment]
Hi @capjamesg , Here is our weight via HuggingFace. https://huggingface.co/spaces/An-619/FastSAM/resolve/main/weights/FastSAM.pt

**Comment by capjamesg** [comment]
Thank you, @berry-ding! I appreciate it!
