### ISSUE TITLE
which part can we fine tune?

### ISSUE THREAD

**Issue by Zhuoyao1012** [CASIA-IVA-Lab/FastSAM#94]
Hi, I have gone through the codes, and found that there's nothing can be trained in the decoder. I'm a little curious which part of the model can be fine tuned, or this project is only a yolov8-seg model trained on SAM generated datasets?

**Comment by zxDeepDiver** [comment]
The finetuning strategy is still under experiments. The main part of this version of FastSAM is yolov8-seg.

**Comment by Zhuoyao1012** [comment]
OK, so there would be a transformer like trainable decoder in the future right?

**Comment by zxDeepDiver** [comment]
> OK, so there would be a transformer like trainable decoder in the future right?

Yes, that is one possibility.
